version: '3.9'

networks:
  default:
    name: backend

services:
  price-service:
    image: 'price-service:latest'
    build: ./
    ports:
      - "8080-8080" # Закрыть после тестов
    container_name: price-service
    env_file:
      - .env
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - DATASOURCE_USERNAME=${POSTGRES_USER}
      - DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - TELEGRAM_BOT_SERVICE_URL=telegram-bot-service:8080

  postgres:
    image: "postgres:latest"
    container_name: "db"
    env_file:
      - .env
    ports:
      - "5432:5432" # Закрыть после тестов
