version: "3.8"

networks:
  default:
    name: backend

services:

  postgres:
    image: postgres:16.1-alpine
    restart: always
    container_name: "db"
    env_file:
      - .env
    ports:
      - "6432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  price-service:
    depends_on:
      - postgres
    image: 'price-service:latest'
    build: ./
    ports:
      - "8080:8080"
    container_name: price-service
    env_file:
      - .env
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/${DATABASE_NAME}
      - DATASOURCE_USERNAME=${DATABASE_USER}
      - DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - TELEGRAM_BOT_SERVICE_URL=telegram-bot-service:8080

volumes:
  db:
    driver: local
