version: '3.9'

networks:
  default:
    name: backend

services:
  postgres:
    image: "postgres:16"
    container_name: "db"
    env_file:
      - .env
    environment:
      PGDATA: "/postgresql/data/pgdata"
    volumes:
      - price-data:/postgresql/data
    ports:
      - "5432:5432" # Закрыть после тестов

  price-service:
    depends_on:
      - postgres
    image: 'price-service:latest'
    build: ./
    ports:
      - "8080:8080" # Закрыть после тестов
    container_name: price-service
    env_file:
      - .env
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - DATASOURCE_USERNAME=${POSTGRES_USER}
      - DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - TELEGRAM_BOT_SERVICE_URL=telegram-bot-service:8080

volumes:
  price-data: