spring:
  application:
    name: price-service
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASSWORD:}
#    driver-class-name: org.postgresql.Driver
  # test
  jpa:
    hibernate:
      ddl-auto: none
  config:
    import: optional:configserver:http://config-server:8080
app:
  best-price:
    period: ${BEST_PRICE_PERIOD:30}
  feign:
    telegram-bot-service: ${TELEGRAM_BOT_SERVICE_URL:http://localhost:8081}
