spring:
  application:
    name: price-service
  datasource:
    url: jdbc:postgresql://localhost:5432/price
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: create
