spring:
  application:
    name: price-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/price}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
app:
  best-price:
    period: ${BEST_PRICE_PERIOD:30}
  feign:
    telegram-bot-service: ${TELEGRAM_BOT_SERVICE_URL:http://localhost:8081}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:29092}
    group-id: ${spring.application.name}
    topics:
      telegram-bot-send: telegram-bot.send
